### ISSUE TITLE
Tag re-pointing updating "latest" but not "develop" branch

### ISSUE THREAD

**Issue by cloudscape-germany** [coreos/quay-docs#98]
Anybody know whats wrong here?

![bildschirmfoto 2017-10-04 um 17 38 17](https://user-images.githubusercontent.com/418352/31184991-2f2e4720-a92b-11e7-89dc-781998804700.png)

**Comment by cloudscape-germany** [comment]
Even worse I have ImagePullPolicy: always and tag to latest and it does not even take that one. Something seems to me to be uterly broken either in tectonic or quay, but this is no fun anymore at the moment.

It is just completely refusing to take the lastest image (I can see it being correctly auto-tagged in quay.io)

```

  image: quay.io/thetaris/superkube:latest
        imagePullPolicy: Always
        name: superkube
        ports:
        - containerPort: 3033
        resources: {}
      restartPolicy: Always
```

I then went on to other measures and created a new tag (k8s), and the deployment is STILL REFUSING to take that. what the heck is going on here?

```
 image: 'quay.io/thetaris/superkube:k8s'
      imageID: >-
        docker-pullable://quay.io/mycompany/superkube:k8s@sha256:0fbdf844408508c410bd46086afbc632ad662055eb829571dd2a6dd4e4819519
```

I now deleted ALL tags except ONE tag pointing to ONE image, nothing else is in there, NOTHING. Guess what, that deployment STILL takes the image that I dont want it to take, that is not tagged even. I consider this a bug now.
